[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlane = "3.3.1"

[profile.dev]
incremental = true
opt-level = 3
lto = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
